version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network

  token-service:
    build: ./components/token-service
    environment:
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./components/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./components/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
