version: '3.8'
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
          - 5672:5672
          - 15672:15672
  gateway:
    image: nginx:alpine
    container_name: gateway
    depends_on:
      - auth-app
      - interviews-app
      - frontend
    volumes:
      - ./components/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"

  auth-db:
    container_name: auth-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - authdb:/var/lib/postgresql/data

  interviews-db:
    container_name: interviews-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interviews
    volumes:
      - interviewsdb:/var/lib/postgresql/data

  reports-db:
    container_name: reports-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reports
    volumes:
      - reportsdb:/var/lib/postgresql/data
  
  token-service:
    build: 
      context: ./components/token-service/
      dockerfile: Dockerfile.dev
    environment:
      - JWT_SECRET=this-is-a-very-secret-key-okay-asdjhjasjdhajkshdkjashdkj
    volumes:
      - ./components/token-service:/app
      - /app/node_modules

  auth-app:
    build: 
      context: ./apps/auth/
      dockerfile: Dockerfile.dev
    
    depends_on:
      - auth-db
      - token-service
    links:
      - auth-db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@auth-db/auth
      - TOKEN_SERVICE_URL=http://token-service:3000
    volumes:
      - ./apps/auth:/app
      - /app/node_modules
    
  
  interviews-app:
    build: 
      context: ./apps/interviews/
      dockerfile: Dockerfile.dev
    depends_on:
      - interviews-db
      - token-service
    links:
      - interviews-db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@interviews-db/interviews
      - TOKEN_SERVICE_URL=http://token-service:3000
      - RABBIT_URL=amqp://rabbitmq:5672
    volumes:
      - ./apps/interviews:/app
      - /app/node_modules
  
  reports-app:
    build: 
      context: ./apps/reports/
      dockerfile: Dockerfile.dev
    depends_on:
      - reports-db
      - token-service
    links:
      - reports-db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@reports-db/reports
      - TOKEN_SERVICE_URL=http://token-service:3000
      - RABBIT_URL=amqp://rabbitmq:5672
    volumes:
      - ./apps/reports:/app
      - /app/node_modules
    
  frontend: 
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - 24678:24678
    volumes:
      - ./apps/frontend:/frontend
      - /frontend/node_modules
      - /frontend/.output
      - /frontend/.nuxt
    environment:
      - API_BASE_URL=/api
    
volumes:
  authdb:
  interviewsdb:
  reportsdb:

networks:
  default:
