name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare project
        run: make prepare

      - name: Run unit tests
        run: make unit-test

      # - name: Run integration tests
      #   run: make integration-test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          apt-get update
          apt-get install -y sshpass
          sshpass -p "$VPS_PASSWORD" scp -o StrictHostKeyChecking=no docker-compose.yml $VPS_USER@$VPS_IP:/interview-ai
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "
            cd /interview-ai
            docker-compose pull
            docker-compose up -d
          "
